---
kind: pipeline
type: docker
name: pull_request

steps:
  - name: build
    image: node:14-alpine
    commands:
      - npm install
      - npm run build
  - name: lint
    image: node:14-alpine
    commands:
      - npm run lint
    depends_on:
      - build

trigger:
  branch:
    - main
  event:
    - pull_request

---
kind: pipeline
type: docker
name: deploy

steps:
  - name: build-prod
    image: node:14-alpine
    commands:
      - npm install
      - npm run build

  - name: deploy-to-aws
    image: node:14-alpine
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    commands:
      - npm install -g serverless
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - serverless
    depends_on:
      - build-prod

  - name: lighthouse-ci
    image: node:14-alpine
    commands:
      - npm install -g @lhci/cli@0.8.x
      - lhci autorun
    depends_on:
      - deploy-to-aws

trigger:
  branch:
    - main
  event:
    - push
